import { Injectable } from '@nestjs/common';
import {
  Prisma,
  ReportFormat,
  ReportJobStatus,
  ReportType,
} from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';
import { ReportFilters } from '../types';

export interface EnqueueInput {
  requestedBy: string;
  reportType: ReportType;
  format: ReportFormat;
  filters: ReportFilters;
  timezone: string;
}

export interface PersistCompletedInput {
  fileName: string;
  contentType: string;
  sizeBytes: number;
  resultData: Buffer | null;
  expiresAt: Date;
}

/**
 * Prisma models `ByteA` columns as `Uint8Array<ArrayBuffer>`; a Node `Buffer`
 * is `Uint8Array<ArrayBufferLike>`, so copy into a plain Uint8Array at the
 * write boundary. `null` is preserved (oversized files are not stored).
 */
function toBytes(data: Buffer | null): Uint8Array<ArrayBuffer> | null {
  return data === null ? null : new Uint8Array(data);
}

export interface ClaimedJob {
  id: string;
  requested_by: string;
  reportType: ReportType;
  format: ReportFormat;
  filters: ReportFilters;
  timezone: string;
  attempts: number;
  max_attempts: number;
  requester: { full_name: string; email: string };
}

/**
 * Persistence + work-queue access for `pharmacy.report_jobs`.
 *
 * Because Redis is unavailable in this deployment, the table is the queue:
 * `claim()` uses `SELECT … FOR UPDATE SKIP LOCKED` so multiple pollers can run
 * without handing the same job to two workers, and a `locked_until` lease lets a
 * job be re-claimed if its worker dies. Abandoned jobs that exhausted retries
 * are transitioned to `FAILED` on the next poll.
 */
@Injectable()
export class ReportJobsRepository {
  constructor(private readonly prisma: PrismaService) {}

  async enqueue(input: EnqueueInput) {
    return this.prisma.reportJob.create({
      data: {
        requested_by: input.requestedBy,
        reportType: input.reportType,
        format: input.format,
        status: ReportJobStatus.QUEUED,
        filters: input.filters as Prisma.InputJsonValue,
        timezone: input.timezone,
      },
      include: { requester: { select: { full_name: true, email: true } } },
    });
  }

  /** Persists a synchronously-generated report as an already-completed job. */
  async createCompleted(input: EnqueueInput, file: PersistCompletedInput) {
    const now = new Date();
    return this.prisma.reportJob.create({
      data: {
        requested_by: input.requestedBy,
        reportType: input.reportType,
        format: input.format,
        status: ReportJobStatus.COMPLETED,
        filters: input.filters as Prisma.InputJsonValue,
        timezone: input.timezone,
        requested_at: now,
        started_at: now,
        completed_at: now,
        attempts: 1,
        file_name: file.fileName,
        content_type: file.contentType,
        size_bytes: file.sizeBytes,
        result_data: toBytes(file.resultData),
        expires_at: file.expiresAt,
      },
      include: { requester: { select: { full_name: true, email: true } } },
    });
  }

  async findById(id: string) {
    return this.prisma.reportJob.findUnique({
      where: { id },
      include: { requester: { select: { full_name: true, email: true } } },
    });
  }

  /** Loads the raw file bytes for download (kept out of list responses). */
  async loadDownload(id: string) {
    return this.prisma.reportJob.findUnique({
      where: { id },
      select: {
        id: true,
        status: true,
        file_name: true,
        content_type: true,
        result_data: true,
        requested_by: true,
        expires_at: true,
      },
    });
  }

  /**
   * Paginated job listing. `result_data` is omitted from the projection so list
   * responses never carry the (potentially large) generated bytes.
   */
  async findMany(query: {
    requestedBy?: string;
    reportType?: ReportType;
    status?: ReportJobStatus;
    page: number;
    pageSize: number;
  }) {
    const where: Prisma.ReportJobWhereInput = {};
    if (query.requestedBy) where.requested_by = query.requestedBy;
    if (query.reportType) where.reportType = query.reportType;
    if (query.status) where.status = query.status;

    const [data, total] = await Promise.all([
      this.prisma.reportJob.findMany({
        where,
        orderBy: { requested_at: 'desc' },
        skip: (query.page - 1) * query.pageSize,
        take: query.pageSize,
        omit: { result_data: true },
        include: { requester: { select: { full_name: true } } },
      }),
      this.prisma.reportJob.count({ where }),
    ]);
    return [data, total] as const;
  }

  /**
   * Atomically claim one runnable job. Returns the claimed job (already flipped
   * to PROCESSING with an incremented attempt counter) or `null` when idle.
   */
  async claim(workerId: string, leaseSec: number): Promise<ClaimedJob | null> {
    return this.prisma.$transaction(async (tx) => {
      // Self-heal: jobs left PROCESSING past their lease with no retries left.
      await tx.$executeRaw`
        UPDATE pharmacy.report_jobs
        SET status = 'FAILED'::pharmacy."ReportJobStatus",
            error_code = 'LEASE_EXPIRED',
            error_message = 'Worker lease expired after exhausting retries',
            completed_at = now()
        WHERE status = 'PROCESSING'::pharmacy."ReportJobStatus"
          AND locked_until < now()
          AND attempts >= max_attempts
      `;

      const candidates = await tx.$queryRaw<Array<{ id: string }>>`
        SELECT id
        FROM pharmacy.report_jobs
        WHERE attempts < max_attempts
          AND (
            status = 'QUEUED'::pharmacy."ReportJobStatus"
            OR (status = 'PROCESSING'::pharmacy."ReportJobStatus" AND locked_until < now())
          )
        ORDER BY requested_at ASC
        FOR UPDATE SKIP LOCKED
        LIMIT 1
      `;
      if (candidates.length === 0) return null;

      const { id } = candidates[0];
      const updated = await tx.$executeRaw`
        UPDATE pharmacy.report_jobs
        SET status = 'PROCESSING'::pharmacy."ReportJobStatus",
            started_at = COALESCE(started_at, now()),
            attempts = attempts + 1,
            locked_until = now() + (${leaseSec})::int * interval '1 second',
            worker_id = ${workerId}
        WHERE id = ${id}::uuid
      `;
      if (updated === 0) return null;

      const job = await tx.reportJob.findUnique({
        where: { id },
        include: { requester: { select: { full_name: true, email: true } } },
      });
      if (!job) return null;
      return {
        id: job.id,
        requested_by: job.requested_by,
        reportType: job.reportType,
        format: job.format,
        filters: (job.filters ?? {}) as ReportFilters,
        timezone: job.timezone,
        attempts: job.attempts,
        max_attempts: job.max_attempts,
        requester: job.requester,
      };
    });
  }

  async markCompleted(id: string, file: PersistCompletedInput): Promise<void> {
    await this.prisma.reportJob.update({
      where: { id },
      data: {
        status: ReportJobStatus.COMPLETED,
        completed_at: new Date(),
        locked_until: null,
        file_name: file.fileName,
        content_type: file.contentType,
        size_bytes: file.sizeBytes,
        result_data: toBytes(file.resultData),
        expires_at: file.expiresAt,
        error_code: null,
        error_message: null,
      },
    });
  }

  async markFailed(
    id: string,
    errorCode: string,
    errorMessage: string,
  ): Promise<void> {
    await this.prisma.reportJob.update({
      where: { id },
      data: {
        status: ReportJobStatus.FAILED,
        completed_at: new Date(),
        locked_until: null,
        error_code: errorCode,
        error_message: errorMessage,
      },
    });
  }

  /** Re-queues a job that still has retries left after a failed attempt. */
  async releaseForRetry(id: string, errorMessage: string): Promise<void> {
    await this.prisma.reportJob.update({
      where: { id },
      data: {
        status: ReportJobStatus.QUEUED,
        locked_until: null,
        error_code: 'RETRY_SCHEDULED',
        error_message: errorMessage,
      },
    });
  }

  /** Deletes generated bytes for completed reports past their retention window. */
  async purgeExpired(): Promise<number> {
    const result = await this.prisma.reportJob.updateMany({
      where: {
        status: ReportJobStatus.COMPLETED,
        expires_at: { lt: new Date() },
        result_data: { not: null },
      },
      data: { result_data: null },
    });
    return result.count;
  }
}
